added logging sub-module
tqdm/tqdm pull request #1155
Opened 2021-04-01 19:35 UTC by de-code

this implements a slightly improved version of #786

2021-04-01 20:42 UTC, de-code commented on tqdm/cli.py
> +from __future__ import absolute_import
this is only required for Python 2 support, if we keep the `logging` submodule name

2021-04-03 00:52 UTC, casperdcl requested changes
this is great. Perhaps should be in `tqdm.contrib.logging` or even just `tqdm.contrib.__init__` for now?

https://github.com/tqdm/tqdm/#redirecting-writing still uses `tqdm.contrib` for the `stdout/err` redirection.

2021-04-03 09:34 UTC, de-code commented
> this is great. Perhaps should be in `tqdm.contrib.logging` or even just `tqdm.contrib.__init__` for now?
> 
> https://github.com/tqdm/tqdm/#redirecting-writing still uses `tqdm.contrib` for the `stdout/err` redirection.

I moved it to `tqdm.contrib.logging` for now. It might be good to have a separate module just for the logging related functions.
I also moved the tests accordingly (there didn't seem to be any tests for contrib yet).
I also added a section to the README.

2021-04-05 23:54 UTC, casperdcl commented
fixes #786

2021-04-05 23:55 UTC, merged

2021-05-25 13:08 UTC, casperdcl commented
Hah @cthoyt it's a well overdue implementation of #786 - just never had enough free time to action it sooner; sorry. Full credit to @de-code though for one of the cleanest code PRs I've seen on this site.

user | additions | deletions
---- | --------- | ---------
@de-code | +429 | -0
@casperdcl | +102 | -170

It may look like I modded a lot but most of that was documentation, not code.